add_newline = false

# Disable 2 line promp
[line_break]
disabled = true

[character]
success_symbol = ""
error_symbol = "[ ✖ ](#BF616A) "

[cmd_duration]
min_time = 10_000  # Show command duration over 10,000 milliseconds (=10 sec)
format = " [took $duration](#8FBCBB)"

[directory]
read_only = " "
truncation_length = 5
format = "[$path](#8FBCBB)[$lock_symbol]($lock_style) "

[git_branch]
format = " [$symbol$branch](#D08770) "
symbol = " "
style = "bold yellow"

[git_commit]
commit_hash_length = 8
style = "bold white"

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
style = "#EBCB8B"

[git_status]
conflicted = " ﲅ  "
ahead = "輪 ×${count} "
behind = "倫 ×${count} "
diverged = "ﲅ  輪 ×${ahead_count} 倫 ×${behind_count} "
untracked = "  ×${count} "
stashed = "  "
modified = " ×${count} "
staged = " ×${count} "
renamed = "璘 ×${count} "
deleted = " ×${count} "
format = "[$all_status](#EBCB8B)$ahead_behind"

[hostname]
ssh_only = false
format = "<[$hostname]($style)>"
trim_at = "-"
style = "bold dimmed white"
disabled = true

[username]
format = "[$user](#5E81AC) "
show_always = true

[memory_usage]
symbol = " "
format = "$symbol[${ram}( | ${swap})]($style) "
threshold = 90
style = "bold #D08770"
disabled = false

[aws]
symbol = "  "
style = "#D08770"

[conda]
symbol = " "

[dart]
symbol = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[golang]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
style = "#A3BE8C"

[package]
disabled=true

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "
style = "#A3BE8C"

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "

[shlvl]
symbol = " "

[swift]
symbol = "ﯣ "
